/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam;

/**
 *
 * @author Sairam
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class view extends javax.swing.JFrame {
    DefaultTableModel model;
    //DefaultTableModel model1;
    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        
        jButton7.setVisible(false);
        
        model=new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("Stud_id");
         model.addColumn("Stud_name");
          model.addColumn("Class");
           model.addColumn("Roll No");
            model.addColumn("Mobile No");
             model.addColumn("Branch");
             model.addColumn("Year");
               model.addColumn("Acoount no.");
                model.addColumn("amount");
                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setEnabled(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 740, 240));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("View payment details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View Student Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 320, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Enter student ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 80, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Search Record");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("View all records");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("LogOut");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, -1, -1));

        jLabel3.setText("Stud Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, -1, -1));

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 70, 100, -1));

        jLabel4.setText("Stud name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 100, -1));

        jLabel5.setText("Class");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 130, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 130, 100, -1));

        jLabel6.setText("Roll No");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, 100, -1));

        jLabel7.setText("Mo No");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 190, 100, -1));

        jLabel8.setText("Branch");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, -1, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 220, 100, -1));

        jLabel9.setText("year");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, -1, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 250, 100, -1));

        jLabel10.setText("Acc No");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, -1, -1));

        jTextField8.setEditable(false);
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 280, 100, -1));

        jLabel11.setText("Amount");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 310, -1, -1));

        jTextField9.setEditable(false);
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 310, 100, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Modify Record");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        
        //String s=(String) jComboBox1.getSelectedItem();
        try
            {
                Class.forName("com.mysql.jdbc.Driver");
		java.sql.Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/exam","riddhi","password");
                
                java.sql.Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select stud.stud_id,stud_name,class,roll_no,mob_no,branch,year,acc_no,amount from stud join account on stud.stud_id=account.stud_id;");
                
                while(rs.next())
                {
                    int id=rs.getInt(1);
                    String nm=rs.getString(2);
                    String clas=rs.getString(3);
                    int rno=rs.getInt(4);
                    String mob=rs.getString(5);
                    String br=rs.getString(6);
                    String year=rs.getString(7);
                    String ano=rs.getString(8);
                    int amt=rs.getInt(9);
                    
                    
                    model.addRow(new Object[]{id,nm,clas,rno,mob,br,year,ano,amt});
                }
            }
        catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        try
            {
                Class.forName("com.mysql.jdbc.Driver");
		java.sql.Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/exam","riddhi","password");
                
                java.sql.Statement st=con.createStatement();
                
                ResultSet rs=st.executeQuery("(select s.stud_id,s.stud_name,s.class,s.roll_no,s.mob_no,s.branch,s.year,p.acc_no,p.amount from stud s left join account p ON s.stud_id=p.stud_id)UNION(select s.stud_id,stud_name,s.class,s.roll_no,s.mob_no,s.branch,s.year,p.acc_no,p.amount from stud s right join account p ON s.stud_id=p.stud_id);");
                System.out.println("connection");
                while(rs.next())
                {
                    int id=rs.getInt(1);
                    String nm=rs.getString(2);
                    String clas=rs.getString(3);
                    int rno=rs.getInt(4);
                    String mob=rs.getString(5);
                    String br=rs.getString(6);
                    String year=rs.getString(7);
                    String ano=rs.getString(8);
                    int amt=rs.getInt(9);
                    
                    model.addRow(new Object[]{id,nm,clas,rno,mob,br,year,ano,amt});
                    //model.fireTableDataChanged();
                }
            }
        catch(Exception e){
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        login1 t2=new login1();
        view.this.setVisible(false);
        t2.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        
        String s=(String) jComboBox1.getSelectedItem();
        //int id=Integer.parseInt(jTextField1.getText());
        try
            {
                 Class.forName("com.mysql.jdbc.Driver");
		java.sql.Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/exam","riddhi","password");
                
                java.sql.Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("Select stud.stud_id,stud_name,class,roll_no,mob_no,branch,year,acc_no,amount from stud left join account on stud.stud_id=account.stud_id where stud.stud_id='"+s+"' ");
                
                while(rs.next())
                {
                    int id=rs.getInt(1);
                    String nm=rs.getString(2);
                    String clas=rs.getString(3);
                    int rno=rs.getInt(4);
                    String mob=rs.getString(5);
                    String br=rs.getString(6);
                    String year=rs.getString(7);
                    String ano=rs.getString(8);
                    int amt=rs.getInt(9);
                    
                    model.addRow(new Object[]{id,nm,clas,rno,mob,br,year,ano,amt});
                    
                    jLabel3.setVisible(true);
                    jLabel4.setVisible(true);
                    jLabel5.setVisible(true);
                    jLabel6.setVisible(true);
                    jLabel7.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel9.setVisible(true);
                    jLabel10.setVisible(true);
                    jLabel11.setVisible(true);
        
                    jTextField1.setVisible(true);
                    jTextField2.setVisible(true);
                    jTextField3.setVisible(true);
                    jTextField4.setVisible(true);
                    jTextField5.setVisible(true);
                    jTextField6.setVisible(true);
                    jTextField7.setVisible(true);
                    jTextField8.setVisible(true);
                    jTextField9.setVisible(true);
        
                    jButton7.setVisible(true);
        
                    model=(DefaultTableModel) jTable1.getModel();
                    jTextField1.setText(Integer.toString(id));
                    jTextField2.setText(nm);
                    jTextField3.setText(clas);
                    jTextField4.setText(Integer.toString(rno));
                    jTextField5.setText(mob);
                    jTextField6.setText(br);
                    jTextField7.setText(year);
                    jTextField8.setText(ano);
                    jTextField9.setText(Integer.toString(amt));
                    
                }
            }
                catch(Exception e){}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //boolean flag=false;
        try
            {
                Class.forName("com.mysql.jdbc.Driver");
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/exam","riddhi","password");
                
                
                PreparedStatement ps;
                
                
                String s1 = jTextField2.getText();
                String s2 = jTextField3.getText();
                int c2 = Integer.parseInt(jTextField4.getText());
                String s3 = jTextField5.getText();
                String s4 = jTextField6.getText();
                String s5 = jTextField7.getText();
                String c3 = jTextField8.getText();
                int c4 = Integer.parseInt(jTextField9.getText());
                
                //System.out.println(c4);
                int c1 = Integer.parseInt(jTextField1.getText());
                if(c4==0)
                { 
                    //flag=true;
                    ps=con.prepareStatement("update stud set stud_name=?,class=?,roll_no=?,mob_no=?,branch=?,year=? where stud_id=?;");
                    ps.setString(1, s1);
                    ps.setString(2,s2);
                    ps.setInt(3, c2);
                    ps.setString(4,s3);
                    ps.setString(5, s4);
                    ps.setString(6,s5);
                    ps.setInt(7,c1);
                    System.out.println("Visited");
                }
                else
                {
                    ps=con.prepareStatement("update stud inner join account ON stud.stud_id=account.stud_id set stud.stud_name=?,class=?,roll_no=?,mob_no=?,branch=?,year=?,account.acc_no=?,amount=? where stud.stud_id=?;");  
                    ps.setString(1, s1);
                    ps.setString(2,s2);
                    ps.setInt(3, c2);
                    ps.setString(4,s3);
                    ps.setString(5, s4);
                    ps.setString(6,s5);
                    ps.setString(7,c3);
                    ps.setInt(8,c4);
                    ps.setInt(9, c1);
                    System.out.println("Visited else");
                }
                
                
                
                
                int rowsUpdated=ps.executeUpdate();
                if(rowsUpdated>0)
                {
                    JOptionPane.showMessageDialog(null, "Rocord is updated Successfully");
                }
            }
        catch(ClassNotFoundException | SQLException | NumberFormatException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
